name: Release

on:
  push

env:
  WGPU_NATIVE_SHA: 7643e9ff7f25e0059f5fb5b62923b5b483551418

jobs:
  release-build:
    name: release-build - ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux-64
            os: ubuntu-18.04
            ARCH: 64
            OS_NAME: linux
          - name: MacOS-64
            os: macOS-10.15
            ARCH: 64
            OS_NAME: macos
          - name: Windows-64
            os: windows-2019
            ARCH: 64
            OS_NAME: windows
    steps:
    - name: Checkout wgpu-native
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        repository: 'gfx-rs/wgpu-native'
        ref: ${{env.WGPU_NATIVE_SHA}}
    - name: Install Linux Dependencies
      if: success() && matrix.OS_NAME == 'Linux'
      run: |
          sudo apt-get update
          sudo apt-get install -f -y libegl1-mesa-dev
          sudo apt-get install -f -y mesa-vulkan-drivers
    - name: Install Windows Dependencies
      if: success() && matrix.OS_NAME == 'windows'
      run: choco install -y --force llvm | exit 0
      shell: bash
    - name: Host build
      if: success()
      run:
          make package
      shell: bash
    - name: Pre-publish
      env:
        OS_NAME: ${{ matrix.OS_NAME }}
        ARCH: ${{ matrix.ARCH }}
      run: |
          mkdir -p ./dist
          mv dist/*debug*.zip ./dist/wgpu-$OS_NAME-$ARCH-debug.zip
          mv dist/*release*.zip ./dist/wgpu-$OS_NAME-$ARCH-release.zip
      shell: bash
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        path: dist
        name: dist

  # Create a Github release and upload the binary libs that we just built.
  # There should be a release and debug build for each os (win32, win64, MacOS64, Linux32, Linux64),
  # plus a file containing the commit sha.
  publish:
    name: Publish Github release
    needs: [release-build]
    runs-on: ubuntu-18.04
    if: success()
    steps:
    - uses: actions/checkout@v2
    - name: Download assets
      uses: actions/download-artifact@v1.0.0
      with:
        name: dist
    - name: Create commit-sha file
      run: |
        echo $WGPU_NATIVE_SHA > dist/commit-sha
    - name: Get version from git ref
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: V.${{env.WGPU_NATIVE_SHA}}
        release_name: Commit ${{env.WGPU_NATIVE_SHA}}
        body: |
            Commit: [${{env.WGPU_NATIVE_SHA}}](https://github.com/gfx-rs/wgpu-native/commit/${{env.WGPU_NATIVE_SHA}})
        draft: false
        prerelease: false
    - name: Upload Release Assets
      # Move back to official action after fix https://github.com/actions/upload-release-asset/issues/4
      uses: AButler/upload-release-assets@v2.0
      with:
        release-tag: V.${{env.WGPU_NATIVE_SHA}}
        files: 'dist/*.zip;dist/commit-sha'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
